apiVersion: v1
kind: Service
metadata:
  name: zarf-vite-template-connect
  labels:
    # Enables "zarf connect zarf-vite-template"
    zarf.dev/connect-name: zarf-vite-template
    app: zarf-vite-template
  annotations:
    zarf.dev/connect-description: "The Vite React application"
spec:
  selector:
    app: zarf-vite-template
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80

